### ISSUE TITLE
Atualização do readme.

### ISSUE THREAD

**Issue by fvieir** [LeandroPedroso14/My-landing-page#1]
Ola Leandro, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para atualização do readme.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by LeandroPedroso14** [comment]
Olá, Fabrício.

Estou bem obrigado, e você como está?

Seguindo as suas ótimas recomendações, fiz algumas alterações.

Obrigado pela disposição, é sempre bom ter alguns feedbacks.

Forte abraço. 👍
