### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by fvieir** [LeandroPedroso14/My-landing-page#2]
Fala Leandro, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para entrega do deploy.

Para deploy você pode usar o netlify, mas sinta-se livre para usar outras plataformas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by LeandroPedroso14** [comment]
Olá! Fabrício.

Estou bem! Obrigado! E você? Como está?

O deploy está concluído, obrigado pelas dicas e orientação, utilizei o netlify como você me recomendou.

Ainda pretendo melhorar vários itens da página, acrescentar mais opções, e adicionar mais conteúdo.

Forte abraço! 👍
